config/routes.rb
Rails.application.routes.draw do
  get '/food/index', to: 'home#index'
  get '/food/:id', to: 'food#index', as: 'food'
  get 'home/index'
  get 'login/index'
  get 'profile/index'
  get 'sessions/new'
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  match ':controller(/:action(/:id))' , :via => :get
  root 'welcome#index'

  get '/rand_food' => 'home#food'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :user_name, presence: true, length: { maximum: 50 },
                    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  #Optional Password Rules
  #validates :password, presence: true, length: { minimum: 6 }
end

app/models/user_food_record.rb
class UserFoodRecord < ApplicationRecord
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
end

app/models/weather.rb
class Weather < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def index
    @food = Food.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sample
  	@controller_message = "Hello From Controller"
  end

  def food
  	@food_origin = params[:food_origin]
  	@food_type = params[:food_type]
  	#TODO: add parameter checking
  	if @food_origin != "" && @food_type != ""
  		@food = Food.where("food_origin = ? and food_type = ?", @food_origin, @food_type).sample
  	elsif @food_origin != ""
  		@food = Food.where("food_origin =?", @food_origin).sample
  	elsif @food_type != ""
  		@food = Food.where("food_type =?", @food_type).sample
  	else
  		@food = Food.order("RAND()").first
  	end

  	respond_to do |format|               
    format.js #renders partial _food.html.erb
  end        
end 
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
require 'httparty'

class ProfileController < ActionController::Base
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def create
    
    # etc
  end


  # GET /users
  def index
    @users = User.all

    @weather = HTTParty.get('http://api.openweathermap.org/data/2.5/weather?q=vancouver,ca&appid=14690f349339811822071d5e32bc915f&units=metric',
    :headers =>{'Content-Type' => 'application/json'} )

    #prints the weather JSON obj
    puts @weather
    
    @weather_icon = @weather["weather"][0]["icon"].to_s
    puts @weather_icon
    #@username = User.find(params[:user_name])||current_user
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_name: params[:session][:user_name].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to home_index_url
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = "Welcome to the feedMi App. User was successfully created."
        format.html { redirect_to :controller => 'home', :action => 'index' }
      else
        flash[:success] = "Welcome to the feedMi App. User was not successfully created."
        format.html { render 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :password_confirmation, :email, :user_name, :first_name, :last_name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def help
    # put any code here that you need 
    # (although for a static view you probably won't have any)
  end
  def index
  	@user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def check_admin
    if current_user.name == "admin"
      return true
    else
      return false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>feedMi</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
  'data-turbolinks-track': 'reload' %>
  <script>
    var map, infoWindow, hereMarker, pos, markerCount;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 0, lng: 0},
        zoom: 14
      });
      infoWindow = new google.maps.InfoWindow();


      // Get user location, then find restaurants nearby
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };

          hereMarker = new google.maps.Marker({
            map: map,
            position: pos
          });

          infoWindow.setPosition(pos);
          infoWindow.setContent('You are here!');
          infoWindow.open(map, hereMarker);


          google.maps.event.addListener(hereMarker, 'click', function() {
            infoWindow.setContent('You are here!');
            infoWindow.open(map, this);
          });

          map.setCenter(pos);
          markerCount = 0;
          getFoodRestaurantsNearby(map, pos);
          if (markerCount < 5) {
          getOriginRestaurantsNearby(map, pos);
          }
        }, function() {
          handleLocationError(true, infoWindow, map.getCenter());
        });
      } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }
    }

    function getFoodRestaurantsNearby(map, pos) {
      var foodName = "<%= @food.food_name %>";

      //Do a place search for restaurants nearby
      var placeService = new google.maps.places.PlacesService(map);
      placeService.nearbySearch({
        location: pos,
        radius: 3000,
        keyword: foodName,
        type: ['restaurant']
      }, callback);
    }

    function getOriginRestaurantsNearby(map, pos) {
      var foodOrigin = "<%= @food.food_origin %>";

      //Do a place search for restaurants nearby
      var placeService = new google.maps.places.PlacesService(map);
      placeService.nearbySearch({
        location: pos,
        radius: 3000,
        keyword: foodOrigin,
        type: ['restaurant']
      }, callback);
    }

    function callback(results, status) {
      if (status === google.maps.places.PlacesServiceStatus.OK) {
        for (var i = 0; i < results.length; i++) {
          createMarker(results[i]);
        }
      }
    }

    function createMarker(place) {
      var placeLoc = place.geometry.location;
      var marker = new google.maps.Marker({
        map: map,
        position: place.geometry.location
      });

      google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent('<div><strong>' + place.name + '</strong><br>' +
                place.vicinity + '<br>' +
                'Rating: ' + place.rating  +'</div>');
        infoWindow.open(map, this);
      });
    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
      infoWindow.setPosition(pos);
      infoWindow.setContent(browserHasGeolocation ?
                            'Error: Please turn on location services.' :
                            'Error: Your browser doesn\'t support geolocation.');
      infoWindow.open(map);
    }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD90bDSQmkeoB_dLU9x82FtOAYPweWKQVg&libraries=places&callback=initMap">
  </script>
  <script>
    function retrieveSearchResults(response) {
      if (response.items == undefined) {
        let noResultsText = 'Sorry! Could not find any recipes for <%= @food.food_name %>';
        let noResults = document.createTextNode(noResultsText);
        document.getElementById("searchResults").appendChild(noResults);
      } else {
        for (var i = 0; i < response.items.length; i++) {
          let item = response.items[i];
          let resLink = document.createElement('a');
          let resLinkText = document.createTextNode(item.title);
          let resBreak = document.createElement('br');
          resLink.appendChild(resLinkText);
          resLink.innerHtml = item.htmlTitle;
          resLink.href = item.link;
          document.getElementById("searchResults").appendChild(resLink);
          document.getElementById("searchResults").appendChild(resBreak);
        }
      }
    }
  </script>
  <script async defer
    src="https://www.googleapis.com/customsearch/v1?key=AIzaSyAILSunC6tE7KYoFfezidpemG_JN-6SrZM&cx=005349411452458523555:asc2vvdzm0o&q=<%= @food.food_name %>&callback=retrieveSearchResults">
  </script>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to("feedMi", {:controller => 'home', :action => 'index'}, id: "logo")%>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Home", {:controller => 'home', :action => 'index'}) %></li>
          <li><%= link_to("Profile", {:controller => 'profile', :action => 'index'}) %></li>
          <li><%= link_to("Sign Out", {:controller => 'welcome', :action => 'index'}) %>
          </ul>
        </nav>
      </div>
    </header>
    <div>
      <%= link_to("Go Back", {:controller => 'home', :action => 'index'}, class: "btn btn-default")%>
      <div class="split left">
        <div class="centered">
          <h1>Recipes</h1>
          <p>Here are some Recipes!</p>
          <%= @food.id %>
          <%= @food.food_name %>
          <%= @food.food_origin %>
          <%= @food.food_type %>
        </div>
        <div id="searchResults" class="results"></div>
      </div>

      <div class="split right">
        <div class="centered">
          <h1>Restaurants</h1>
          <p>Here are some Restaraunts!</p>
          <%= @food.id %>
          <%= @food.food_name %>
          <%= @food.food_origin %>
          <%= @food.food_type %>
        </div>
        <div id="map" class="map"></div>
    </div>
  </body>
  </html>

app/views/home/_food.html.erb
<div id = "food_sect">
	<% if @food.nil? == false %>
		<%= @food.id %>
		<%= @food.food_name %>
		<%= @food.food_origin %>
		<%= @food.food_type %>
    <div>
    <%= link_to("I pick this food!", {:controller => 'food', :action => @food.id}, class: "btn btn-default")%>
    </div>
	<% else %>
		<%= "Could not find a food for you :(" %>
	<% end %>
</div>

app/views/home/food.js.erb
$('#food_div').html("<%= escape_javascript(render :partial => 'food') %>");

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>feedMi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to("feedMi", {:controller => 'home', :action => 'index'}, id: "logo")%>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to("Home", {:controller => 'home', :action => 'index'}) %></li>
            <li><%= link_to("Profile", {:controller => 'profile', :action => 'index'}) %></li>
            <li><%= link_to("Sign Out", {:controller => 'welcome', :action => 'index'}) %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="center jumbotron">
      <h1>Welcome to feedMi</h1>

      <h2>
        This is the home page.
      </h2>

      <div>
        <%= form_tag("/rand_food", method: "get", :remote => true) do %>
          <%= submit_tag("RANDOMIZE!") %>
          <!-- TODO: selection of one filter should pre-filter choices for other select dropdown -->
          <%= select_tag(:food_origin, options_from_collection_for_select(Food.pluck(:food_origin).uniq, 'strip', 'strip'), {:include_blank => 'Filter food origin'}) %>
          <%= select_tag(:food_type, options_from_collection_for_select(Food.pluck(:food_type).uniq, 'strip', 'strip'), {:include_blank => 'Filter food type'}) %>
        <% end %>  
        <div id = "food_div"></div>
      </div>
    </div>
  </body>
</html>

app/views/home/sample.html.erb
<h1>Home#sample</h1>
<p>Find me in app/views/home/sample.html.erb</p>



<%= " Message from controller :
#{@controller_message}" %>

app/views/login/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>feedMi</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
  'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to("feedMi", {:controller => 'welcome', :action => 'index'}, id: "logo")%>

    </div>
  </header>
  <div>

   <h1>Log in</h1>

   <div class="row">
     <div class="col-md-6 col-md-offset-3">
       <%= form_for(:session, url: login_path) do |f| %>

       <%= f.label :user_name %>
       <%= f.text_field :user_name, class: 'form-control' %>

       <%= f.label :password %>
       <%= f.password_field :password, class: 'form-control' %>

       <%= f.submit "Log in", class: "btn btn-primary" %>
       <% end %>

     </br>
     <p>New user? <%= link_to "Sign up now!", {:controller => 'welcome', :action => 'index'} %></p>
     
   </div>
 </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :FirstName %>
    <%= form.text_field :John, id: :user_firstname %>
  </div>

  <div class="field">
    <%= form.label :LastName %>
    <%= form.text_field :smith, id: :user_lastname %>
  </div>

  <div class="field">
    <%= form.label :UserName %>
    <%= form.text_field :food, id: :user_username %>
  </div>


  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

   <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>feedMi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to("feedMi", {:controller => 'welcome', :action => 'index'}, id: "logo")%>
        <nav>
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to("Log In", {:controller => 'login', :action => 'index'}) %></li>

          </ul>
        </nav>
      </div>
    </header>
    <div class="center jumbotron">
      <h1>Welcome to feedMi</h1>

      <h2>
        This is the Welcome page to feedMi. Sign up Below!
      </h2>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@user) do |f| %>

            <%= render 'shared/error_messages' %>

            <%= f.label :user_name %>
            <%= f.text_field :user_name, class: 'form-control' %>

            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :confirm_password %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Sign up now!", class: "btn btn-primary" %>
          <% end %>

        </div>
      </div>
    </div>

  </body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>feedMi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to("feedMi", {:controller => 'welcome', :action => 'index'}, id: "logo")%>
        <nav>
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to("Log In", {:controller => 'login', :action => 'index'}) %></li>

          </ul>
        </nav>
      </div>
    </header>
    <div class="center jumbotron">
      <h1>Welcome to feedMi</h1>

      <h2>
        This is the Welcome page to feedMi. Sign up Below!
      </h2>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for @user.new do |f| %>

            <%= f.label :user_name %>
            <%= f.text_field :user_name, class: 'form-control' %>

            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :confirm_password %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Sign up now!", class: "btn btn-primary" %>
          <% end %>

        </div>
      </div>
    </div>

  </body>
</html>

app/views/welcome/sample.html.erb
<h1>Welcome#sample</h1>
<p>Find me in app/views/welcome/sample.html.erb</p>



<%= " Message from controller :
#{@controller_message}" %>